In [45]:
import pandas as pd
import numpy as np
from scipy.spatial import distance

In [214]:
class kmeans():  
    
    def __self__(k):
        self.cluster = k
        self.max_iter = 100

    def fit(self, X, k):

        converged = False       
        X = np.array(X) # convert df to numpy array    
                
        centroids_idx = np.random.choice(range(X.shape[0]), k) # random initialization of k centroids
        centroids = X[[centroids_idx]]
        new_centroids = np.zeros((k,X.shape[1]))
        iter = 0

        while not converged and iter <300:
            labels = []
            cnt = [[0]] * k
            for point in X:
                idx = np.argmin([distance.euclidean(i, point) for i in centroids])
                new_centroids[idx] = new_centroids[idx] + point
                cnt[idx] = [cnt[idx][0]+1]
                labels.append(idx)
            
            new_centroids = new_centroids / np.array(cnt)
#             print(centroids)
#             print(cnt)
            diff = np.array([distance.euclidean(i,j) for i in new_centroids for j in centroids])
            centroids = new_centroids
            if all(abs(diff) < 0.001): 
                converged = True
                self.labels = labels
                self.centroids = centroids
            else: 
                iter += 1
                continue
                
        print(new_centroids)

In [219]:
X = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[2,4,6],[1,4,5],[3,5,6],[1,2,9],[4,5,20],[1,8,9],[2,4,30],[1,8,5],[3,5,11],[3,2,3],[6,5,6],[9,8,9],[6,4,6],[4,4,5],[3,5,7]],columns=['f1','f2','f3'])
mykmeans = kmeans()
mykmeans.fit(X, 3)

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  del sys.path[0]


[[ 4.61067983  5.94404623 10.23182619]
 [ 2.6         4.6        12.4       ]
 [ 5.18842233  7.19953372  8.89359855]]


In [220]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(a)
kmeans.cluster_centers_

array([[ 2.91666667,  4.16666667,  5.58333333],
       [ 3.        ,  4.5       , 25.        ],
       [ 5.        ,  7.25      ,  9.5       ]])