In [45]:
import pandas as pd
import numpy as np
from scipy.spatial import distance

In [146]:
class knn():  
    
    def __self__(k):
        self.cluster = k
        self.max_iter = 100

    # define fit function
    def fit(self, X, k):

        converged = False       
        X = np.array(X) # convert df to numpy array    
                
        centroids_idx = np.random.choice(range(X.shape[0]), k) # random initialization of k centroids
        centroids = X[[centroids_idx]]
        new_centroids = np.zeros((k,X.shape[1]))
        iter = 0

        while not converged and iter <100:
            labels = []
            for point in X:
                idx = np.argmin([distance.euclidean(i, point) for i in centroids])
                new_centroids[idx] = new_centroids[idx] + point
                labels.append(idx)
            
            new_centroids = new_centroids / X.shape[0]
            print(centroids)
            diff = np.array([distance.euclidean(i,j) for i in new_centroids for j in centroids])
            centroids = new_centroids
            if all(abs(diff) < 0.001): 
                converged = True
                self.labels = labels
                self.centroids = centroids
            else: 
                iter += 1
                continue

In [147]:
a = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[2,4,6],[1,4,5],[3,5,6],[1,2,9],[4,5,20],[1,8,9],[2,4,30],[1,8,5],[3,5,11],[3,2,3],[6,5,6],[9,8,9],[6,4,6],[4,4,5],[3,5,7]],columns=['f1','f2','f3'])
aaa = knn()
aaa.fit(a,2)

[[3 2 3]
 [6 5 6]]
[[24.44444444 41.77777778 83.44444444]
 [39.94444444 51.11111111 80.16666667]]
[[39.35802469 51.32098765 80.63580247]
 [25.2191358  41.83950617 83.4537037 ]]
[[25.18655693 41.85116598 83.4797668 ]
 [39.4010631  51.32441701 80.63631687]]
[[39.39925316 51.32506478 80.63776482]
 [25.18894795 41.8513565  83.47979538]]
[[25.1888474  41.85139249 83.47987582]
 [39.399386   51.32507536 80.63776641]]
[[39.39938041 51.32507736 80.63777088]
 [25.18885478 41.85139308 83.47987591]]
[[25.18885447 41.85139319 83.47987616]
 [39.39938082 51.32507739 80.63777088]]
[[39.3993808  51.3250774  80.6377709 ]
 [25.18885449 41.85139319 83.47987616]]
[[25.18885449 41.85139319 83.47987616]
 [39.39938081 51.3250774  80.6377709 ]]
[[39.3993808  51.3250774  80.6377709 ]
 [25.18885449 41.85139319 83.47987616]]
[[25.18885449 41.85139319 83.47987616]
 [39.3993808  51.3250774  80.6377709 ]]
[[39.3993808  51.3250774  80.6377709 ]
 [25.18885449 41.85139319 83.47987616]]
[[25.18885449 41.85139319 83.4798

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  
